name: Test Homebrew formula

on: push

jobs:
  build:
    name: Test Homebrew formula
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
      - name: Test formula
        run: |
          brew audit cumulusci.rb
          brew install cumulusci.rb
          brew test cumulusci.rb
